% halftone images are generated by error diffusion [1]
% input_para.mat is trained from the halftone images

% [1] B. E. Bayer, "An optimum method for two-level rendition of continuous-tone pictures",
%       in Proceeding IEEE International Communication Con-ference, 1973, pp. 2611-2615.


clear; clc;

% the messages length, embed m bits
m = 1024;

% imread binary image as cover
cover = logical(imread('1.bmp'));

% embed message using STC by single-pixel strategy
stego = embed(cover, m, 'single');

% embed message using STC by muliti-layer strategy
% stego = embed(cover, m, 'multi');

diff = abs(double(cover)- double(stego));

subplot(1,3,1)
imshow(cover, []);
title('The cover image');
subplot(1,3,2)
imshow(stego, []);
title('The stego image');
subplot(1,3,3)
imshow(diff, []);
title('The different image');



